- src/EbmlElement.cpp
similar to when reading the element id
> detect EOF when reading the element size

- src/EbmlElement.cpp
The size check waas also missing from the length parsing
> Check the max size to read before actually reading

- src/EbmlElement.cpp
The test `MaxDataSize >= (PossibleID_Length + PossibleSizeLength + SizeFound)`
is incorrect when there was garbage data skipped inside the PossibleIdNLength
table.
Now we keep track of how many memmove we had to do to know the real position of
the PossibleIdNLength data since we started reading. That allows a proper check
on the end value since that start.
> Rework the way we look at the end boundary when looking an element in a parent

- CMakeLists.txt
remove WinIO from the build
remove useless winapifamily check
> Cmake cleaning

- CMakeLists.txt
> allow building WinIOCallback conditionally

- ebml/c/libebml_t.h
Original patch was written by Adrien Destugues @pulkomandy
> libebml, add patch for type definitions for Haiku.

- ChangeLog
- src/EbmlString.cpp
- src/EbmlUnicodeString.cpp
> include appropriate header files for std::numeric_limits

- src/EbmlMaster.cpp
> std::find conversions

- .github/workflows/linux-gcc10.yaml
- .github/workflows/linux.yaml
- .github/workflows/macos.yaml
- .github/workflows/windows.yaml
- README.md
I'd like to add gcc10 test after that
> CI: add a basic compilation test

- CMakeLists.txt
- NEWS.md
- ebml/EbmlVersion.h
- src/EbmlVersion.cpp
> bump soname to 6 due to ABI-breaking changes & bump version number

- src/EbmlMaster.cpp
> push_back conversion

- .github/workflows/linux-gcc10.yaml
- .github/workflows/linux.yaml
- .github/workflows/macos.yaml
- .github/workflows/windows.yaml
Not entirely sure it will do what I suppose it does.
> [1.x] do 1.x build actions when pushing to the v1.x branch

- ebml/EbmlBinary.h
- ebml/EbmlConfig.h
- ebml/StdIOCallback.h
We require a proper C++14 compiler.
> remove BorlandC hacks

- ebml/EbmlBinary.h
- ebml/EbmlConfig.h
- ebml/EbmlElement.h
- ebml/EbmlEndian.h
- ebml/EbmlTypes.h
- ebml/StdIOCallback.h
- src/EbmlBinary.cpp
- src/EbmlCrc32.cpp
- src/EbmlDate.cpp
- src/EbmlUnicodeString.cpp
- src/IOCallback.cpp
- src/StdIOCallback.cpp
The version text doesn't match the code anymore.
> remove confusing SVN version tag

- .github/workflows/windows.yaml
- src/platform/win32/WinIOCallback.cpp
- src/platform/win32/WinIOCallback.h
> Fix Windows CreateFile return check

- ebml/EbmlElement.h
so we can declare all classes the same way
> add missing DECLARE_EBML_xxx macros

- CMakeLists.txt
- NEWS.md
- ebml/EbmlVersion.h
- src/EbmlVersion.cpp
I'd like to release v1.4.5 soon. The only fix was the potential access beyond allocated memory due to missing checks for integer addition overflows.
> V1x release 145

- .github/workflows/linux-gcc13.yaml
It should provide better source checking,
> build with gcc13 instead of gcc10

- .github/workflows/linux-gcc13.yaml
It should provide better source checking,
> [1.x] build with gcc13 instead of gcc10

- .github/workflows/linux-gcc13.yaml
This is the most likely (only) platform where building dynamically might be used.
> CI: build Linux in static and shared versions

- CMakeLists.txt
- test/test_header.cxx
This should help figuring out the issues in #186.
And we can also track issues in future code changes.
> add a test to write/read an EBML header

- CMakeLists.txt
> switch to C++17

- ebml/EbmlMaster.h
- src/EbmlElement.cpp
> Simplify calls to compute the HeadSize

- .github/dependabot.yml
- .github/workflows/linux-gcc13.yaml
- .github/workflows/linux.yaml
- .github/workflows/macos.yaml
- .github/workflows/uwp.yaml
- .github/workflows/windows.yaml
v3 issues some warning of deprecated stuff.
> CI: use actions/checkout@v4 + dependabot on actions

- ebml/EbmlElement.h
- src/EbmlSInteger.cpp
- src/EbmlUInteger.cpp
Since 5529b1e4754c39dd9a9f89e1e49c1cf4c404316b
> silence possible variable shadowing warning

- src/EbmlUnicodeString.cpp
> use if constexpr for always constant test known at compilation time

- CMakeLists.txt
And disable dynamic builds on Windows as on 2.0
Mostly cherry picks of 2.0
> [1.x] add option summary

- .gitignore
- src/lib/utf8-cpp/LICENSE
- src/lib/utf8-cpp/README.md
- src/lib/utf8-cpp/source/utf8.h
- src/lib/utf8-cpp/source/utf8/checked.h
- src/lib/utf8-cpp/source/utf8/core.h
- src/lib/utf8-cpp/source/utf8/cpp20.h
- src/lib/utf8-cpp/source/utf8/unchecked.h
Copied straight from https://github.com/nemtrif/utfcpp/tree/v4.0.6 (without the CMake and other parts)
> Update utf8 library to latest 4.0.6 version

- .github/workflows/abibreak.yaml
- .github/workflows/linux-gcc13.yaml
- .github/workflows/linux.yaml
- .github/workflows/macos.yaml
- .github/workflows/windows.yaml
That gives cleaner logs and might be slightly faster.
> [1.x] build with Ninja
