configure.ac
ebml/EbmlConfig.h

so we disable debug for these targets

code for Windows App Store do not have access to the ANSI calls used in Debug.cpp

---

ebml/EbmlBinary.h

Needed when compiling with clang/libc++.

Add cstdlib for free/malloc.

---

ebml/EbmlMaster.h
src/EbmlElement.cpp
src/StdIOCallback.cpp

These fixes are to fix/quiet warnings that are enabled by default in new Xcode projects, such as DoxyGen documentation and unreachable code.

Xcode warnings fixes

---

src/EbmlElement.cpp

Similar to what is done in FindNextID().
SetSizeInfinite() doesn't actually set anything. SetSizeIsFinite() is the one
that actually sets it and it is an internal API.

Do not output an element with size Unknown if it's not allowed

---

src/EbmlElement.cpp

DataStream.getFilePointer() is not correct in this context. It might force to
exit too early.

Exit the max size loop when there's nothing left possible to find

---

ebml/EbmlMaster.h

Otherwise GetSize() returns an invalid size that is used to compute the size
length.

fix GetDataStart() for elements read with an infinite size

---

CMakeLists.txt
ebml/EbmlConfig.h
ebml/EbmlElement.h
ebml/EbmlVersion.h
ebml/SafeReadIOCallback.h

This pull request closes #8 and closes #36.
* Generate new public header `ebml_export.h` with [GENERATE_EXPORT_HEADER](https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html) standard macro
* Export classes which Visual Studio wants to be exported when built as DLL
* Change export define as CMake wants: is was `EBML` when building shared library; now it is `EBML_STATIC_DEFINE` for static builds.

Fix export symbols when build as Windows DLL

---

CMakeLists.txt
EbmlConfig.cmake
EbmlConfig.cmake.in
ebml/EbmlElement.h

* Adds ebml exported target to EBML:: namespace as recommended
* Set uniform `${CMAKE_PACKAGE_INSTALLDIR}` to make it simpler
* Properly set `EBML_FOUND` variable when `EBML` is searched in config mode

CMake fixes

---

ebml/EbmlCrc32.h

Fixes: warning C4138: '*/' found outside of comment

warning C4138 fix for #57

---

ebml/MemIOCallback.h

Minor safety change, allowing to call MemIOCallback::GetDataBufferSize() for const objects.

Minor safety change in MemIOCallback.h

---

src/EbmlBinary.cpp
src/EbmlCrc32.cpp
src/EbmlDate.cpp
src/EbmlFloat.cpp
src/EbmlSInteger.cpp
src/EbmlString.cpp
src/EbmlUInteger.cpp
src/EbmlUnicodeString.cpp

* some strings may read huge size into small memory buffers on 32 bits systems
* some integer/float are trying to read large sizes on fixed (8 bytes) buffers
There were some asserts but in release builds that won't trigger anything and just write in out of bounds memory.
If we can't read we just pretend that we have read the data. But `SetValueIsSet()` is not called. Just like we do for other errors we already handle.
Fixes #74

Fix misc reading overflows

---

src/EbmlCrc32.cpp

Since this is C++11 now, might as well use constexpr to replace some
macros.
Originally found with bugprone-macro-usage.

replace crc32 macros with constexpr function

---

CMakeLists.txt

MSVC 2022 no longer supports C++11. Fixes warning:
WARNING: msvc does not support C++11; attempting best effort; setting the standard to C++14

CMakeLists: update to c++14

---

ebml/EbmlDate.h
src/EbmlDate.cpp

Fixes a linking issue when trying to compile as a DLL on Windows.

initialize UnixEpochDelay in declaration

---

src/EbmlMaster.cpp

This is an address of a reference. It cannot be null.

remove nullptr check

---

ebml/EbmlElement.h
src/EbmlBinary.cpp
src/EbmlCrc32.cpp
src/EbmlElement.cpp
src/EbmlMaster.cpp
src/EbmlSInteger.cpp
src/EbmlUnicodeString.cpp
src/EbmlVoid.cpp
src/IOCallback.cpp
src/SafeReadIOCallback.cpp
src/StdIOCallback.cpp

The `EbmlElement: use size_t for HeadSize()` is breaking API and ABI. Since we're breaking ABI in 1.5.0 that should be OK.
Ref. #105

Fix misc MSVC warnings

---

src/StdIOCallback.cpp

On Windows min and max are macros. So some parenthesis around the method call are needed to use the proper code.
The old comment about cygwin should be fixed. A C++14 compiler should have no problem with this.

Use C++ Numeric limits where possible

---

CMakeLists.txt
NEWS.md
ebml/EbmlVersion.h
ebml/IOCallback.h
ebml/MemIOCallback.h
ebml/MemReadIOCallback.h
ebml/StdIOCallback.h
src/EbmlVersion.cpp
src/MemIOCallback.cpp
src/MemReadIOCallback.cpp
src/StdIOCallback.cpp

Fixes #108.
The function is supposed to return the number of bytes actually read. As it takes a "number of bytes to read" parameter of type `size_t`, it cannot signal success properly if the number of bytes to read exceeds the size of its former return type, `uint32`, which is 4 GB.
This breaks the API & the ABI. Users of this class hierarchy have to adjust their overrides as well.

change return type of IOCallback::read() to size_t

---

ebml/EbmlBinary.h
src/EbmlBinary.cpp

An implicit one is deprecated as of C++11 and gcc throws warnings.

add defaulted operator= constructor

---

CMakeLists.txt
NEWS.md
ebml/EbmlBinary.h
ebml/EbmlDate.h
ebml/EbmlElement.h
ebml/EbmlUnicodeString.h
ebml/EbmlVersion.h
src/EbmlBinary.cpp
src/EbmlDate.cpp
src/EbmlElement.cpp
src/EbmlUnicodeString.cpp
src/EbmlVersion.cpp

Reverting these commits on top of release 1.4.3 fixes the ABI breakage. Tests were done with the tool `abidiff` from `libabigail`.
The goal is to release a version 1.4.4 that's basically just 1.4.3 without the ABI breakage so that distributions can update their packages while we continue working on the API-breaking 2.0.0.
See #104.
I haven't tested this yet against a packaged MKVToolNix that was compiled with 1.4.2; therefore please don't merge yet.
Will do the same thing for libMatroska.

V1.4.4 fix abi breakage

---

ebml/EbmlConfig.h

We do not have a config.h file and it should not be in a public header.
`config.h` and `HAVE_CONFIG_H` is usually used during the build phase.

remove cargo culting of config.h

---

ebml/EbmlConfig.h
ebml/EbmlElement.h

And use a cleaner C++ version. Now it's part of the libebml namespace so it's not mixed with other implementations.

move the countof() helper in EbmlElement where it's used

---

ebml/EbmlConfig.h
src/EbmlUInteger.cpp

EBML_PRETTYLONGINT should not exists as there are standard ways to do it in C++ now.
Also for uint64_t literals we should use UINT64_C found in cstdint, like uint64_t.

Use proper integer literal and remove EBML_PRETTYLONGINT

---

ebml/EbmlTypes.h

wchar_t is not even guaranteed to be on 2 octets

remove unused utf types

---

CMakeLists.txt
ebml/EbmlConfig.h
ebml/EbmlEndian.h
ebml/EbmlTypes.h
src/EbmlCrc32.cpp

All endianess related code is moved into `EbmlEndian.h`
Ony the big endian templates are kept as we don't use the little endian ones. But people can still use the little endian implementation if they want. The implementation is not changed although it is likely inefficient compared to compiler built-in helpers. We could completely redo the big_xxx types in more efficient way and forget about other sizes.
Fixes #122

Misc endian cleanup

---

ebml/EbmlEndian.h
src/EbmlDate.cpp
src/EbmlFloat.cpp
src/IOCallback.cpp
src/MemReadIOCallback.cpp
src/SafeReadIOCallback.cpp

Ultimately we can remove the generic Endian<> class. When compiled with GCC and Clang the bytes reversal can be a simple instruction. It may be the case for MSVC as well.

Add a simpler/faster Endian API for 16/32/64 Big-Endian buffers

---

.github/workflows/linux-gcc10.yaml
.github/workflows/linux.yaml
.github/workflows/macos.yaml
.github/workflows/uwp.yaml
.github/workflows/windows.yaml

Also add a UWP target (the WinIO class doesn't compile yet, which is where it can really be useful).

Build Windows/macOS for multiple architectures

---

NEWS.md
src/MemIOCallback.cpp

dataBufferMemorySize was not being updated properly after realloc in MemIOCallback::write(). When writing the whole MKV file with frames then coming back to update the head of the file, this non-updated dataBufferMemorySize caused realloc in a way reducing the size of the file. This behavior causes loss of the frame data.

Properly update dataBufferMemorySize in MemIOCallback after realloc.

---

src/EbmlElement.cpp

constant values are integers by default anyway

avoid unecessary cast in CodedSizeLengthSigned

---

src/MemIOCallback.cpp

Fix MemIOCallback buffer overflows

---

src/MemIOCallback.cpp

Same as #148 for the 1.x branch.

[1.x] Fix MemIOCallback buffer overflows

---

NEWS.md

This is in preparation for a release of version 2.0.0. Trying to give the remaining developers using the libraries as many hints as possible about what they'll have to fix.

NEWS: update with all the API/ABI breaks merged for version 2.0.0

---

ebml/EbmlBinary.h
ebml/EbmlFloat.h
ebml/EbmlSInteger.h
ebml/EbmlString.h
ebml/EbmlUInteger.h
ebml/EbmlUnicodeString.h
src/EbmlElement.cpp

Please read the commit messages. They explain in great detail what the warnings & fixes are about.

Avoid compiler warnings

---

ebml/EbmlBinary.h
ebml/EbmlCrc32.h
ebml/EbmlDate.h
ebml/EbmlDummy.h
ebml/EbmlElement.h
ebml/EbmlEndian.h
ebml/EbmlFloat.h
ebml/EbmlId.h
ebml/EbmlMaster.h
ebml/EbmlSInteger.h
ebml/EbmlStream.h
ebml/EbmlString.h
ebml/EbmlUInteger.h
ebml/EbmlUnicodeString.h
src/EbmlDummy.cpp
src/EbmlMaster.cpp

So far the code was built without the define. But since we can change the API for 2.0 we should switch to a stricter API that makes things less public.
This requires libmatroska to merge https://github.com/Matroska-Org/libmatroska/pull/95
We might be able to add some `constexpr` here and there despite using methods.

Use the strict access API

---

ebml/EbmlElement.h
src/EbmlElement.cpp

Fixes #145
The relevant code has been moved to libmatroska.

remove unused integer coding callbacks

---

ebml/EbmlElement.h

They are not used anywhere. We don't need to maintain unused code.

Remove Legacy macros/defines

---

src/EbmlMaster.cpp

This will crash in the destructor and many other places.
It's unlikely to happen by better safe than sorry.
This should probably be backported to 1,x

don't keep null clones

---

ebml/EbmlElement.h
src/EbmlElement.cpp
src/EbmlMaster.cpp

This was designed to be able to keep a pointer alive after its parent master element is destroyed. But it's not used anywhere and a C++ refcounting should be used for that.

remove EbmlElement locking

---

ebml/EbmlElement.h

It's used by libmatroska test and even VLC.
Partially reverts db95ac181f310bde1e1c26b5b7eaa6c4bbb54a4b

bring back EBML_CLASS_CONTEXT

---

ebml/EbmlDate.h
ebml/EbmlElement.h
ebml/EbmlId.h
src/EbmlElement.cpp

The API is designed to set the values on creation and not touch them again.
Also change some integer constants so they are more readable.
The `EbmlSemanticContext` cannot be a `constexpr` (for now?) because it's exported as `extern const`.

Make more variables const so we have more constexpr constructors

---

src/EbmlMaster.cpp

This reverts commit ca27cb05f1955a4b8db35edd5935eec613684aae from #162.

Revert "don't keep null clones"

---

CMakeLists.txt
ebml/EbmlBinary.h
ebml/EbmlCrc32.h
ebml/EbmlDate.h
ebml/EbmlDummy.h
ebml/EbmlElement.h
ebml/EbmlFloat.h
ebml/EbmlMaster.h
ebml/EbmlSInteger.h
ebml/EbmlString.h
ebml/EbmlUInteger.h
ebml/EbmlUnicodeString.h
src/EbmlBinary.cpp
src/EbmlCrc32.cpp
src/EbmlElement.cpp
src/EbmlFloat.cpp
src/EbmlHead.cpp
src/EbmlMaster.cpp
src/EbmlSInteger.cpp
src/EbmlString.cpp
src/EbmlUInteger.cpp
src/EbmlUnicodeString.cpp
src/EbmlVoid.cpp
test/test_infinite.cxx

In Matroska only the Segment and Cluster are allowed to do so.
Doing so on elements that are not allowed to will just not do anything and assert in debug builds.
Fixes #167

Only allow some specific Master elements to be set as infinite

---

ebml/EbmlUnicodeString.h
src/EbmlUnicodeString.cpp
test/test_utfstring.cxx

In EBML and in most systems, UTF-8 is used by default. Converting from wchar_t should be the exception and not done for every unicode string we read/write.
**Some API's with wchar_t are gone**. They are not used in VLC (which just deals wtih UTF-8) and in some corresponding `to_wide` functions in mkvtoolnix seem to be unused and can also be removed.
**The length() reported is different.** It now reports the length in bytes of the UTF-8 string which is the length needed to write the buffer in EBML anyway.
This PR also fixes #180.

Rework UTFString API to only keep UTF-8

---

.github/workflows/windows.yaml
CMakeLists.txt

And build dynamic libraries in the Linux CI.

Disable building DLL on Windows

---

ebml/EbmlBinary.h
ebml/EbmlCrc32.h
ebml/EbmlDate.h
ebml/EbmlElement.h
ebml/EbmlFloat.h
ebml/EbmlMaster.h
ebml/EbmlSInteger.h
ebml/EbmlString.h
ebml/EbmlUInteger.h
ebml/EbmlUnicodeString.h
ebml/EbmlVoid.h
src/EbmlBinary.cpp
src/EbmlCrc32.cpp
src/EbmlDate.cpp
src/EbmlElement.cpp
src/EbmlFloat.cpp
src/EbmlMaster.cpp
src/EbmlSInteger.cpp
src/EbmlString.cpp
src/EbmlUInteger.cpp
src/EbmlUnicodeString.cpp
src/EbmlVoid.cpp

And remove the ForceNoDefault() which is not needed anymore.
There's a `EBML_WRITE_FILTER` define to tell between libmatroska versions with this feature or not.

Add a callback to select which element are written

---

ebml/EbmlElement.h

Changed after d6dc50cee690491a2aa8e038e31f2cdc2001c24a.
libmatroska currently doesn't build without this.

fix exported context const

---

ebml/EbmlElement.h

We may clean that later.
Fixes libmatroska build on Windows.

Don't use constexpr for possibly exported EbmlSemanticContext

---

.github/workflows/linux-gcc13.yaml
.github/workflows/linux.yaml
.github/workflows/macos.yaml
.github/workflows/uwp.yaml
.github/workflows/windows.yaml
CMakeLists.txt

If approved I'll do the same with libmatroska.
I did not investigate too much the MSVC options for now.

Add a DEV_MODE option to enable more warnings

---

src/EbmlCrc32.cpp

make_unique will initialize each item to the 0 [1].
[1] https://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique

use a unique_ptr for the temporary zero-padding

---

ebml/SafeReadIOCallback.h
src/SafeReadIOCallback.cpp

This class is only used by libmatroska to wrap an  EbmlBinary. So the API changes will have no impact on external code.

Use shared_ptr for the internal MemReadIOCallback of SafeReadIOCallback

---

ebml/EbmlFloat.h
ebml/EbmlSInteger.h
ebml/EbmlString.h
ebml/EbmlUInteger.h
ebml/EbmlUnicodeString.h
src/EbmlFloat.cpp
src/EbmlSInteger.cpp
src/EbmlString.cpp
src/EbmlUInteger.cpp
src/EbmlUnicodeString.cpp

It requires a complicated assigment syntax for a simple thing.
libmatroska will need https://github.com/Matroska-Org/libmatroska/pull/136 to build

remove operator= base types

---

ebml/EbmlElement.h

So they can be used without forcing the namespace globally.

use the libebml namespace in macros

---

ebml/EbmlDate.h
ebml/EbmlElement.h
ebml/EbmlFloat.h
ebml/EbmlSInteger.h
ebml/EbmlString.h
ebml/EbmlSubHead.h
ebml/EbmlUInteger.h
ebml/EbmlUnicodeString.h
src/EbmlFloat.cpp
src/EbmlMaster.cpp
src/EbmlSInteger.cpp
src/EbmlString.cpp
src/EbmlUInteger.cpp
src/EbmlUnicodeString.cpp
test/test_infinite.cxx
test/test_macros.cxx

A lot of the logic is the same between classes. We can factorize the code once we have factorized the storage (and initialization) types in a template.
The default value is moved to a EbmlCallbacksDefault class for the types that can have a default value. So the default value is not copied in each instance of every object.
~~This was done on top of #173 but maybe it works on its own.~~

Use templates for the base types to factorize code

---

ebml/EbmlDate.h
ebml/EbmlElement.h
ebml/EbmlFloat.h
ebml/EbmlSInteger.h
ebml/EbmlString.h
ebml/EbmlUInteger.h
ebml/EbmlUnicodeString.h
src/EbmlDate.cpp
src/EbmlFloat.cpp
src/EbmlSInteger.cpp
src/EbmlString.cpp
src/EbmlUInteger.cpp
src/EbmlUnicodeString.cpp

Use templates to factorize generic code

---

ebml/EbmlDate.h
ebml/EbmlElement.h
src/EbmlDate.cpp
src/EbmlFloat.cpp
src/EbmlSInteger.cpp
src/EbmlUInteger.cpp

This is how it was before the EbmlElementDefaultSameStorage() split.
Draft on top of ~~#186~~#200

Make the Value private

---

ebml/EbmlDummy.h
ebml/EbmlElement.h
src/EbmlDummy.cpp

We can use ClassInfo directly now. We can also remove the virtual of some methods.

Move some common virtual methods in EbmlElement

---

ebml/EbmlElement.h
src/EbmlElement.cpp
src/EbmlFloat.cpp
src/EbmlMaster.cpp
src/EbmlSInteger.cpp
src/EbmlString.cpp
src/EbmlUInteger.cpp
src/EbmlUnicodeString.cpp

We can add generic code in there. In particular it allows libmatroska to do extra filter that may not be welcome in the more generic libebml.

factorize the calls to the write filter per element

---

ebml/EbmlCrc32.h
ebml/EbmlElement.h

With a template we may only have one macro with a default value for the length...

Allow settling a length constraint on binary elements

---

ebml/EbmlElement.h
src/EbmlElement.cpp

If the size is invalid, we will return nullptr. So let's not create the element in the first place.
The first patch can be backported to 1.x

Create less bogus elements on reading

---

ebml/EbmlMaster.h
src/EbmlMaster.cpp

It's off by default. Not sure we want to keep the constexpr variable.

use a default initializer for the EbmlMaster checksum boolean

---

src/EbmlMaster.cpp

It's easier to use than Read(). The drawback is that it doesn't handle going up a level in case of bogus data.
This can be backported.

implement EbmlMaster::ReadData

---

CMakeLists.txt
src/EbmlMaster.cpp
test/test_crc.cxx
test/test_header.cxx

On top of #215 so there is a test for EbmlMaster::ReadData().

Test checksum writing/reading

---

CMakeLists.txt
ebml/EbmlMaster.h
src/EbmlMaster.cpp
test/test_missing.cxx

It's not used by anyone and is not a core functionality of libebml. It can be done externally as the test shows.

move FindAllMissingElements functionality into a test example

---

ebml/EbmlBinary.h
ebml/EbmlDate.h
ebml/EbmlElement.h
ebml/EbmlFloat.h
ebml/EbmlMaster.h
ebml/EbmlSInteger.h
ebml/EbmlString.h
ebml/EbmlUInteger.h
ebml/EbmlUnicodeString.h
src/EbmlElement.cpp

Rather than ValidateSize() which requires to set the value on the element first, we can check if the size is valid before doing it, or rejecting the element in that case.
~~On top of #212 and #213.~~
It might be possible to get the information from the element specs (and avoid creating an element just to delete right after), but that will be for another Pull Request.

Pass the size to check on an element

---

ebml/EbmlElement.h
src/EbmlBinary.cpp
src/EbmlCrc32.cpp
src/EbmlDummy.cpp
src/EbmlHead.cpp
src/EbmlMaster.cpp
src/EbmlSInteger.cpp
src/EbmlString.cpp
src/EbmlUnicodeString.cpp
src/EbmlVoid.cpp
test/test_infinite.cxx
test/test_macros.cxx

They correspond to the attributes in the EBML specs.
For they are just informational. We may use this information when reading data to find which element are allowed given the read/version in the EBML header, that can help with error recovery, skipping elements that are not legit given the context.

[RFC] keep track of minver and maxver per element

---

src/EbmlMaster.cpp

Not sure if we should make the EbmlMaster constructor throw in this case. There might be some code assuming Mandatory elements are available no matter what. This is also needed in the copy constructor of #162. But it would break the API/ABI so not for 1.x.
This only happens when pushing to a vector fails, so extremely limited memory constraints.

Handle Push element error

---

ebml/EbmlBinary.h
ebml/EbmlCrc32.h
ebml/EbmlDate.h
ebml/EbmlElement.h
ebml/EbmlFloat.h
ebml/EbmlMaster.h
ebml/EbmlSInteger.h
ebml/EbmlString.h
ebml/EbmlUInteger.h
ebml/EbmlUnicodeString.h
ebml/EbmlVoid.h
src/EbmlBinary.cpp
src/EbmlCrc32.cpp
src/EbmlDate.cpp
src/EbmlElement.cpp
src/EbmlFloat.cpp
src/EbmlMaster.cpp
src/EbmlSInteger.cpp
src/EbmlString.cpp
src/EbmlUInteger.cpp
src/EbmlUnicodeString.cpp
src/EbmlVoid.cpp

Too expensive to pass by value.
@robUx4

pass std::function by const ref

---

ebml/EbmlElement.h
ebml/EbmlId.h
src/EbmlCrc32.cpp
src/EbmlDummy.cpp
src/EbmlElement.cpp
src/EbmlHead.cpp
src/EbmlVoid.cpp
test/test_id.cxx
test/test_infinite.cxx
test/test_macros.cxx

Maybe it's possible with std::enable_if but I haven't managed to do it. Not sure it would be usable on reading though.
We don't need to pass the length of the ID anymore (we may not even store it anymore).
libmatroska will need this to build https://github.com/Matroska-Org/libmatroska/pull/169

Rework Id creation to check statically for invalid IDs

---

CMakeLists.txt
ebml/EbmlElement.h
src/EbmlCrc32.cpp
src/EbmlDummy.cpp
src/EbmlHead.cpp
src/EbmlVoid.cpp
test/test_infinite.cxx
test/test_macros.cxx
test/test_versioning.cxx

**This will need an update on the libmatroska side before this is merged.** After this MR it won't be possible to used temporary EbmlDocVersion anymore.
=> https://github.com/Matroska-Org/libebml/pull/228
We now have the EbmlId static+constepr and the Semantic and SemanticContext constexpr. 
A test has been added to test the various issues found with EbmlDocVersion usage.

Keep the usage of temporary EbmlDocVersion instances to init global semantic classes 

---

ebml/EbmlElement.h

On top of https://github.com/Matroska-Org/libebml/pull/207 only the last commit "don't try to write elements that are deprecated" matters here.
The write filter allows to skip gracefully the elements that should never be written. Such elements are currently asserting in RenderData and return 0 there. This would likely break the internals as the written size no longer matches the UpdateSize value. Relying on the write filter fixes this as the same element will be skipped in UpdateSize and in Render(Data).
Eventually it would be nice to remove the RenderData overrides and just rely on this. However whoever implements a custom write filter (mkvtoolnix) should probably take this in consideration. If we remove the overrides we will allow writing deprecated elements in some circumstances, which …

Don't attempt to write deprecated elements

---

ebml/EbmlDummy.h
src/EbmlDummy.cpp

Fixes compilation on GCC7-9 for some reason.

declare EbmlDummy constructor in cpp file

---

src/EbmlCrc32.cpp
src/EbmlHead.cpp

Newer clang is more strict regarding \0 in constexpr.

fix newer clang compile

---

CMakeLists.txt

And make sure clang doesn't pretend to use compiler flags when it just ignores them.

generate a warning for alignement issues

---

ebml/EbmlElement.h

GCC7 errors on this. Creator is not a constant expression.

remove assert

---

CMakeLists.txt

Most of the have already been fixed.

cmake: remove various warning suppressions

---

src/EbmlCrc32.cpp

Non x86 platforms are more strict about alignment and thus throw a Wcast-align warning on these two reinterpret_casts. Use memcpy to avoid.

fix cast-align error

---

CMakeLists.txt

They are very noisy and not very useful.
the list of warnings can be found at https://learn.microsoft.com/en-us/cpp/preprocessor/compiler-warnings-that-are-off-by-default

disable most verbose warnings in MSVC in Dev Mode

---

ebml/EbmlElement.h
ebml/EbmlEndian.h
ebml/EbmlId.h
ebml/EbmlTypes.h
ebml/IOCallback.h
ebml/SafeReadIOCallback.h
src/EbmlDate.cpp
src/EbmlFloat.cpp
src/EbmlUnicodeString.cpp
src/MemIOCallback.cpp
src/StdIOCallback.cpp

Now `EbmlTypes.h` only defines libebml types. `EbmlEndian.h` is only included where it's used.

Cleanup includes in public headers

---

src/EbmlCrc32.cpp

We cannot write any other size than 4.

Simplify CRC32 writing

---

ebml/StdIOCallback.h
src/EbmlBinary.cpp
src/StdIOCallback.cpp

It's not used explicitly in mkvtoolnix or VLC.

Use more standard exceptions and remove CRTError exception

---

ebml/EbmlEndian.h

`reinterpret_cast` doesn't generate any code, it just let the compiler a type conversion is happening. So the generated code should be the same.
However on the output the generated code might have been converted resulting to bogus values (used in dates and floats).

Fix sign conversion in MSVC byte swapping

---

ebml/EbmlDate.h
src/EbmlBinary.cpp
src/EbmlMaster.cpp

All filtered out elements should give a size of 0. The result is usually not used but the result should be consistent.
It's already done this way for most elements.

add missing filter checks in UpdateSize()

---

src/EbmlVoid.cpp

* Honor the filtering of elements (void or replacement) that are not allowed to be written.
* Rework the algorithm to compute the new data size/size length combination of the Void element

Rework EbmlVoid internals

---

ebml/MemIOCallback.h
src/MemIOCallback.cpp

Missing from 701f7b2a290f4e8acbcd99a116a9c8a91d351de7.
That API seems to be unused.

fix MemIOCallback IOCallback write return type

---

src/EbmlElement.cpp

ReadSize is assigned in multiple places but never actually used.

remove unused variable

---

CMakeLists.txt

It generates a warning with newer versions of CMake. 3.4 was released in 2015. We require C++17 with compilers only available in 2017/2018. If your CMake is older than your toolchain, you have a problem.
There's no need to support legacy CMake going forward in libebml 2.

drop CMake older than 3.5

---

ebml/EbmlElement.h
ebml/EbmlMaster.h
src/EbmlVoid.cpp

The Head size is rarely needed and may be 0 depending on writing filter.
Draft on top of #255

make EbmlElement::HeadSize private 

---

ebml/EbmlDummy.h
ebml/EbmlElement.h
src/EbmlDummy.cpp
src/EbmlElement.cpp
src/EbmlMaster.cpp
test/test_crc.cxx
test/test_header.cxx

We can do with less methods and reuse the methods that already exist to do the same calls.
That will make things easier to maintain.

Reduce the number of methods and cleanup some macros

---

ebml/EbmlElement.h

Extracted from #264 
Also fixes issues with the removed `EbmlCallbacks &` operator.

Add macros and reuse macros

---

ebml/EbmlElement.h

We have stronger typing and have the better idea of how they should be called.
Once downside is that they are not grouped together anymore.
~~Depends on #265~~

Turn main EBML macros into static inlines

---

src/EbmlMaster.cpp

`test_crc` still passes after this.

don't capture anything while looking for a CRC32 element

---

src/EbmlBinary.cpp
src/EbmlElement.cpp
src/EbmlFloat.cpp
src/EbmlMaster.cpp
src/EbmlSInteger.cpp
src/EbmlString.cpp
src/EbmlUInteger.cpp
src/EbmlUnicodeString.cpp

Although filepos_t is a std::uint64_t it's better to use the proper type.

fix UpdateSize return type

---

ebml/EbmlElement.h
src/EbmlCrc32.cpp
src/EbmlDummy.cpp
src/EbmlHead.cpp
src/EbmlVoid.cpp
test/test_infinite.cxx
test/test_macros.cxx
test/test_versioning.cxx

Otherwise we can differentiate with subclasses.
Different element may come from different spaces (ebml and matroska).

add a "namespace" to the EbmlDocVersion

---

ebml/EbmlMaster.h
ebml/EbmlStream.h
src/EbmlMaster.cpp
test/test_missing.cxx

`FindElt()` is a duplicate of `FindFirstElt()`.
This will require https://github.com/Matroska-Org/libmatroska/pull/190 for libmatroska as it was using `FindElt()` (and vice versa for the extra const).

Make more use of typed children macros and remove FindElt

---

ebml/EbmlMaster.h
ebml/EbmlStream.h
src/EbmlMaster.cpp
test/test_missing.cxx

Reverts Matroska-Org/libebml#285
Unfortunately I merged to soon: many segfaults in MKVToolNix. Haven't debugged it yet.

Revert "Make more use of typed children macros and remove FindElt"

---

ebml/EbmlVersion.h
src/EbmlVersion.cpp

Unused except in a libmatroska test that is removed in https://github.com/Matroska-Org/libmatroska/pull/192

remove deprecated EbmlCodeDate string

---

ebml/EbmlContexts.h
ebml/EbmlElement.h
ebml/EbmlMaster.h
src/EbmlContexts.cpp
src/EbmlElement.cpp
src/EbmlMaster.cpp
test/test_macros.cxx
test/test_missing.cxx

The internal are reworked so only semantic context of EbmlMaster elements have a table of possible children.
"[Get]ElementSpec()" is generalized so there's stronger typing of the semantic context for all the types.
The callback to get the global elements now returns a `EbmlSemanticContextMaster`. Ultimately it only needs to return a container with a list of semantic context.

Don't export EbmlMaster context, use the class static member

---

src/EbmlUnicodeString.cpp

Compilation breaks when the `algorithm` header isn't included indirectly anymore. This happens with certain combinations of compiler/C++ library/C++ mode, e.g. clang++ 17/libstdc++ 14.1/C++20

fix compilation by including header in which std::find is defined

---

ebml/EbmlDummy.h
ebml/EbmlElement.h
ebml/EbmlId.h
src/EbmlDummy.cpp
test/test_macros.cxx

Match the exact values allowed in RFC 8794 Table 4 and 17.1 Ebml ID registry with errata https://www.rfc-editor.org/rfc/rfc8794.html#tableElementIDRanges https://www.rfc-editor.org/rfc/rfc8794.html#name-ebml-element-ids-registry
Not allowing the reserved values 0xFF, 0x7FFF, 0x3FFFFF and 0x1FFFFFFF. As they are reserved value maybe we should allow them in case they are used in the future ? But we don't know how.
`EbmlDummy` uses 0xFF internally which is supposed to be reserved. That ID value is never used but it's still an EbmlId object with a reserved/invalid value.
From the issue raised in https://github.com/Matroska-Org/libebml/commit/5326cfe8a2b81a05ade730ef9c53570d10f6d7ed#commitcomment-147015759

restrict the ranges of valid EBML ID values

---

CMakeLists.txt

It fails to build in the CI because older versions support has been dropped in newer CMake.
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```
This is already done in the master branch.
(cherry picked from commit 6725c5f0169981cb0bd2ee124fbf0d8ca30b762d)

[1.x] CMake: bump minimum CMake version

---

.github/workflows/abibreak.yaml
.github/workflows/linux-gcc13.yaml
.github/workflows/linux.yaml
.github/workflows/macos.yaml
.github/workflows/windows.yaml

v3 issues some warning of deprecated stuff.
(cherry picked from commit f7cc11237cb833fb6b28a9a071952e6d43063b73)

[1.x] CI: use actions/checkout@v4

---

ebml/EbmlDummy.h
ebml/EbmlElement.h

To create a bare EbmlElement we don't need an actual element as in CreateElement(). We just need an EbmlCallbacks which may or may not come from an element.
For now `CreateElement()` is kept for backward compatibility but it can be replaced by an `EBML_CREATE()` call, which can call `CreateElement()` when compiled with libebml 1.x.

Rework element creation
